In [4]:
import numpy as np
from scipy import linalg

In [2]:
x = np.array([[3, 3, 3], [1, 3, 4], [7, 1, 3]])

In [3]:
x

array([[3, 3, 3],
       [1, 3, 4],
       [7, 1, 3]])

In [5]:
a, b = linalg.eig(x)

In [6]:
a

array([ 9.4423844+0.j        , -0.2211922+1.76868245j,
       -0.2211922-1.76868245j])

In [7]:
c = np.array([1, 1, 1, 1, 1])
d = np.array([2])

In [8]:
np.dot(c, d)

ValueError: shapes (5,) and (1,) not aligned: 5 (dim 0) != 1 (dim 0)

In [9]:
e = np.array([[0,9,19,13],[1,20,5,13],[12,11,3,4]])
f = np.array([[2,0,0,0],[1,2,2,0],[2,1,1,0],[0,0,1,1]])

In [27]:
f * e

ValueError: operands could not be broadcast together with shapes (4,4) (3,4) 

In [11]:
b2 = np.array([[-1, 33, 4, 1], [0, 1, 1, 0]])

In [12]:
np.average(b2)

4.875

In [13]:
b3 = np.array([[6, 0, 3], [0, -1, 2], [12, 3, 0]])

In [17]:
a1, a2 = linalg.eig(b3.T)

In [18]:
b3[lambdas == 0,:]

NameError: name 'lambdas' is not defined

In [19]:
x1 = np.array([[1,-1,-1,0], [-1,2,-1,-1],[-1,-1,2,-1],[0,-1,-1,1]])

In [20]:
e1, e2 = linalg.eig(x1)

In [21]:
e1

array([-1.+0.j,  1.+0.j,  3.+0.j,  3.+0.j])

In [22]:
x2 = np.array([[2,4,0,4,1],[2,4,1,1,0],[1,1,1,2,2],[0,1,3,2,4],[2,2,2,0,2]])

In [23]:
x2

array([[2, 4, 0, 4, 1],
       [2, 4, 1, 1, 0],
       [1, 1, 1, 2, 2],
       [0, 1, 3, 2, 4],
       [2, 2, 2, 0, 2]])

In [24]:
x2.T

array([[2, 2, 1, 0, 2],
       [4, 4, 1, 1, 2],
       [0, 1, 1, 3, 2],
       [4, 1, 2, 2, 0],
       [1, 0, 2, 4, 2]])

In [25]:
np.trace(x2.T)

11

In [26]:
np.unique(x2)

array([0, 1, 2, 3, 4])